### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by blumenschwein** [artikell/joplin-excalidraw#2]
I installed this plugin and excalidraw itself. Excalidraw is running correctly in the browser, but this Joplin plugin is not working. When I use ```excalidraw``` and reload the note, I still only see the text but cannot edit anything. The Joplin GUI did not change, either.

I am using Joplin 2.9.11.

**Comment by blumenschwein** [comment]
I figured out: only in 2.8.8 (the latest release version) it is possible to install this plugin. But afterwards, when I removed 2.8.8 and installed 2.9.17, the plugin is still there and works well. 

But this works only for the Windows version. In Ubuntu, the plugin is lost again after Ubuntu has been rebooted.

I wonder if there is some incompatibility during installation?

**Comment by Shahin-rmz** [comment]
same issue here.

**Comment by jorgomezga** [comment]
Same here, not working in Pop-os with Joplin 2.9.17

**Comment by dhdevdk** [comment]
Same here, not working with ubuntu 20.04 and joplin 2.9.17

**Comment by joshuacook-tamu** [comment]
Also not working on MacOS 12.6.2 and Joplin 2.9.17. I don't have the option to enable the Excalidraw interface. It no longer appears in the UI like it did before I upgraded from plugin version 1.0.0

**Comment by stevemagruder** [comment]
Just tried this out today. Not working for me on Windows 10/11 and Joplin 2.10.4. The excalidraw UI isn't launched when re-opening the note with ```excalidraw``` in it.

**Comment by hjstrauss** [comment]
Same here unfortunately, does not work on Windows with Joplin 2.10.4

**Comment by alondmnt** [comment]
possible solution:

1. open Help-->Toggle development tools.
2. look in the log for an error similar to the following one:
```
joplin.plugins: Uncaught exception in plugin "com.joplin.excalidraw": Error: ENOENT: no such file or directory, stat '/var/folders/z8/6_9tvj2d6931fmn5q64r1xjm0000gn/T/joplin-excalidraw-plugin/'
```
3. create the missing directory.
4. restart Joplin.

**Comment by joshuacook-tamu** [comment]
I can confirm that this worked for me. I can now see the excalidraw UI again! I could not see the error until I disabled the plugin, restarted Joplin, enabled the plugin, restarted Joplin and then immediately launched the dev tools. I think the error only shows up early in the life cycle of starting the app. Thanks for sharing this work-around!

**Comment by stevemagruder** [comment]
Yup, I found the error in the console, created the new folder, restarted Joplin, and now excalidraw appears to be working.
Thanks!

**Comment by ei8fdb** [comment]
For the [above work-around](https://github.com/artikell/joplin-excalidraw/issues/2#issuecomment-1436889799) the [discussion thread link](https://discourse.joplinapp.org/t/plugin-support-excalidraw-in-joplin/27686/23?u=bernard).

Does anyone know what needs to happen so that work around isn't needed? It's a pity that a good plug-in may not be used as a result. I'm happy to help in any way.

**Comment by stevemagruder** [comment]
I imagine that In the plugin's code, if it needs a temp directory to exist, it would test for its existence, and if not there, create it. Thus, this is a bug for the developer to fix if they're interested.

**Comment by artikell** [comment]
Sorry, I haven't replied for a long time. Things have been busy recently. I will clean up issue regularly in the future
I really didn't repeat the issue. I'm not sure how you use this plug-in?
There are two methods:
1. use ```excalidraw```, like a code
2. use ```![excalidraw](excalidraw://970d7f3995b94321827cdcb8b9e16dc0)```, like a image
I don't recommend the first method very much, because the management of the plane is very complex and is prone to exceptions. I am ready to remove it. 
Maybe you can give me some information? @stevemagruder @ei8fdb @alondmnt

**Comment by gr4phite** [comment]
What url do we add in the excalidraw part? And how exactly do we add it? Do we just copy-paste the url you put as an example?

EDIT: I did do the \`\`\`excalidraw\`\`\` method, but I don't understand the second one (`![excalidraw](excalidraw://970d7f3995b94321827cdcb8b9e16dc0)`)

**Comment by gr4phite** [comment]
Also, I tried doing the workaround above, but Joplin crashes whenever I write anything. I'm using the Joplin flatpak from flathub.

**Comment by stevemagruder** [comment]
I did nothing but follow the directions on the front page.

Initiate a Excalidraw by writing following in the markdown:

```excalidraw```

**Comment by artikell** [comment]
@Ultra980 I recorded an animation, which may help you use this plug-in?
![example](https://artikell.github.io/images/joplin-excalidraw-example.gif)

**Comment by artikell** [comment]
> possible solution:
> 
> 1. open Help-->Toggle development tools.
> 2. look in the log for an error similar to the following one:
> 
> ```
> joplin.plugins: Uncaught exception in plugin "com.joplin.excalidraw": Error: ENOENT: no such file or directory, stat '/var/folders/z8/6_9tvj2d6931fmn5q64r1xjm0000gn/T/joplin-excalidraw-plugin/'
> ```
> 
> 3. create the missing directory.
> 4. restart Joplin.

I don't know why this problem is unstable. However, I have fixed it in 1.4.1

**Comment by NiklasRosenstein** [comment]
@artikell How can I install v1.4.1? When searching for the plugin in Joplin, it only fins 1.3.0.

![image](https://github.com/artikell/joplin-excalidraw/assets/1318438/c634774c-eab0-4c55-b605-65718af73dea)

**Comment by metal3d** [comment]
For some reasons, I have the 1.3.0 version too. The toolbar doesn't show any button for excalidraw.
