### ISSUE TITLE
outdated version on joplin/plugins

### ISSUE THREAD

**Issue by Mylloon** [artikell/joplin-excalidraw#6]
The version in the official repo is 1.3.0 (https://github.com/joplin/plugins/tree/master/plugins/com.joplin.excalidraw)

**Comment by ethancedwards8** [comment]
Bump, I'm having this issue as well. @artikell

**Comment by alfredopalhares** [comment]
Me to, its still 1.3.0 the plugin button is not loading, not sure if its because its a outdated version of it.

**Comment by ethancedwards8** [comment]
I think the Joplin update bot is broken.

**Comment by helcone** [comment]
I am having the button issue as well.

**Comment by personalizedrefrigerator** [comment]
I think the version of the plugin in `manifest.json` needs to be increased:

https://github.com/artikell/joplin-excalidraw/blob/f5a30360c31d3507f27569ca36788a9b81c77868/src/manifest.json#L5

The update bot determines the plugin's version based on `manifest.json` and not the version on NPM.
